# Build matrix - generates firmware for both nice_nano v1 and v2
# If unsure which board you have, flash v2 first (most common).
# If it doesn't work, flash v1 instead.
# Use settings_reset firmware to clear stored BT/settings if keyboard is stuck.
---
include:
  # ── nice_nano_v2 (most clones and current boards) ──
  - board: nice_nano_v2
    shield: sofle_left nice_oled
  - board: nice_nano_v2
    shield: sofle_right nice_oled
  - board: nice_nano_v2
    shield: settings_reset

  # ── nice_nano v1 (original/legacy) ──
  - board: nice_nano
    shield: sofle_left nice_oled
  - board: nice_nano
    shield: sofle_right nice_oled
  - board: nice_nano
    shield: settings_reset
